"""create job_offers table

Revision ID: f88ede088dd6
Revises: 
Create Date: 2026-04-09 10:12:57.800916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f88ede088dd6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_offers',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('company', sa.String(length=100), nullable=False),
    sa.Column('position', sa.String(length=200), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'REJECTED', 'OFFER_RECEIVED', name='offerstatusenum'), nullable=False),
    sa.Column('current_stage', sa.Enum('RESUME_SENT', 'HR_SCREENING', 'TECH_INTERVIEW', 'TEST_TASK', 'FINAL_INTERVIEW', 'OFFER', name='stagetypeenum'), nullable=False),
    sa.Column('notes', sa.JSON(), nullable=True),
    sa.Column('progress_percentage', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_offers_user_id'), 'job_offers', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_offers_user_id'), table_name='job_offers')
    op.drop_table('job_offers')
    # ### end Alembic commands ###
